### ISSUE TITLE
[FE] 랜딩페이지 디자인 개선

### ISSUE THREAD

**Issue by jong-k** [jong-k/code#1]
## Description
랜딩페이지 개선을 위해 동영상 컴포넌트를 추가하고, GNB의 디자인을 개선합니다

## Todo
- [ ] 최상단 스크롤일 때 투명한 GNB 구현 
- [ ] 스크롤 내려가면 흰 바탕 GNB 구현
- [ ] 자동으로 동영상 재생되는 컴포넌트 추가

## ETC
- 참고 : https://www.ithaka.org/

**Comment by jong-k** [comment]
코끼리가 지나가는 동영상 - 클라우디너리 기본 제공 영상이라 저작권 ok.
멀리 가려면 함께 가세요 텍스트 추가.

**Comment by jong-k** [comment]
참고자료
- pexel
- jstor
- ithaka
- react.dev 의 video 섹션
